### ISSUE TITLE
Files randomly missing  in volume mount from Windows host to Windows container after Windows 10 2004

### ISSUE THREAD

**Issue by KHeresy** [docker/for-win#8093]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 33C611F4-BE15-4CED-A58A-588F8739013F/20200817005404

### Expected behavior

I use Windows container with Visual Studio to build my project in CI/CD stage.

The Docker command like:
```
docker run -v S:\code\prject:c:\code --isolation process --rm MyBuilderImageName msbuild /nowarn:C4005,C4018,C4101,C4244,C4267,C4305,LNK4099 /v:minimal /m /p:Configuration=Release c:\code
```

This works fine before I upgrade Windows 10 to ver.2004.

After I upgrade to Windows 10 2004 (both host OS and Docker image), files may randomly missing when compile.

The missed file may different each time, and sometime it can run successfully without missing files.

### Actual behavior

Project build failed because file missing.

Error message may like:

```
c:\code\external\include\boost\config\abi_prefix.hpp(19,12): fatal error C1083: Cannot open include file: 'boost/config/abi/msvc_prefix.hpp': No such file or directory (compiling source file voxel.cpp) [c:\code\src\render\render.vcxproj]
```

It may build successfully without missing file, or missing another file if I try again.

### Information
  - Is it reproducible?
    - Randomly happen, but high frequency 
  - Did the problem appear with an update?
    - After upgrade Windows to 2004
  - Windows Version: Windows 10 2004 19041.450
  - Docker Desktop Version: 2.3.4.0 (Edge)
  - Docker Desktop Version: 2.3.0.4 (Stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, run in standalone Windows PC
  - Maybe the same issue as #5959 (Linux container)?

### Steps to reproduce the behavior

Dockerfile:
```
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-2004

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools 2019 bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
ADD https://aka.ms/vs/16/release/channel C:\TEMP\VisualStudio.chman

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --installPath C:\BuildTools `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    --add Microsoft.VisualStudio.Component.VC.ATLMFC `
    --add Microsoft.VisualStudio.Component.Windows10SDK.18362

# clean download files
RUN del C:\TEMP\* /q

# Start developer command prompt with any other commands specified.
ENTRYPOINT c:\BuildTools\VC\Auxiliary\Build\vcvars64.bat && 
```

**Comment by stephen-turner** [comment]
Thanks for the report, @KHeresy. As this is Windows containers, the bug must be in the upstream Engine, not in Docker Desktop, as Desktop does not manage the file sharing for Windows containers. So could you please open your issue at https://github.com/moby/moby instead? (Sorry, I would just transfer it if I could, but the engine isn't part of the docker org, and it's not possible to move an issue across orgs).
